### ISSUE TITLE
BUG: Pawn Promotion

### ISSUE THREAD

**Issue by HasanTalouli** [DrexelSTARChess/Server#51]
There is currently a bug where only white pawns are able to be promoted, and only if they move into an empty space.
To fix this bug we need to make it so that both black and white pawns are able to be promoted, even if they enter a space in row eight that is occupied by an enemy piece.

**Comment by TraderJ0s** [comment]
#52 #53 Issue is closed here, added method to handle pawn promotion as well as pawn promotion flag
